version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network  # Assurez-vous que le réseau est bien défini

  app:
    image: php:8.2-fpm  # Mise à jour pour utiliser PHP 8.2
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network  # Assurez-vous que le réseau est bien défini

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
      - ./nginx/logs:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network  # Assurez-vous que le réseau est bien défini

networks:
  app-network:
    driver: bridge
