name: Deploy Site to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install OpenVPN
      run: sudo apt-get update && sudo apt-get install -y openvpn

    - name: Setup VPN
      run: |
        sudo mkdir -p /etc/openvpn
        echo "${{ secrets.VPN_CONFIG }}" > config.ovpn
        sudo mv config.ovpn /etc/openvpn/config.ovpn
        echo -e "${{ secrets.ENT_USERNAME }}\n${{ secrets.ENT_PASSWORD }}" | sudo tee /etc/openvpn/ent_credentials > /dev/null
        sudo sed -i 's/auth-user-pass/auth-user-pass \/etc\/openvpn\/ent_credentials/' /etc/openvpn/config.ovpn
        sudo openvpn --config /etc/openvpn/config.ovpn --daemon
        sleep 10 # Attendre que la connexion VPN soit établie
        sudo cat /var/log/syslog | grep openvpn # Afficher les journaux OpenVPN pour le débogage

    - name: Verify VPN Connection
      run: |
        ping -c 4 10.1.138.4

    - name: Setup SSH Key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H 10.1.138.4 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh etudiant@10.1.138.4 << 'EOF'
          cd /home/etudiant/AutoMarket &&
          git pull &&
          docker-compose down &&
          docker-compose up -d --build
        EOF