name: Deploy Site to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 10.1.138.4 >> ~/.ssh/known_hosts
        eval $(ssh-agent -s)
        echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null

    - name: Deploy to server
      run: |
        ssh etudiant@10.1.138.4 << 'EOF'
          cd /home/etudiant/AutoMarket &&
          git pull &&
          docker-compose down &&
          docker-compose up -d --build
        EOF
